{% set version = "1.6.0" %}

package:
  name: cycamore
  version: {{ version }}

source:
  git_url: https://github.com/cyclus/cycamore.git
  git_rev: 1.6.0

build:
  number: 3
  skip: True  # [win or osx or py<310]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - make
    - pkg-config
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cyclus {{ version }}
  run:
    - python
    - cyclus {{ version }}

test:
  requires:
    - pytest
    - pytables
  source_files:
    - input
    - tests

about:
  home: http://fuelcycle.org/
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: "The Cyclus additional modules repository."

extra:
  recipe-maintainers:
    - gonuke
    - katyhuff
    - FlanFlanagan
    - bennibbelink
    - munkm
    - abachma2
