travis:
  secure:
    BINSTAR_TOKEN: M6DdrXFbNX7i/2r8vJYciybdw9TiKOlXqX9up+qASzq+Gx8QB78dT0UA5t1sOaKzMQplSV0s3F/ZUuDiUmsiDd1ZTH/L7teYNvJKy4s5y3foPkGO1Ah4yhuHzboQhO07Sbk8FTG5Er2RaEu0EhmeApmHC0P58HTXVdXmx9BakRs5SWf4yBRcSTc4nDNLYjXl+Kgn0iCUqkQE7OIEaogVniDStmYn6Lcs7hojSV/50gnlsQIc+v4l8qnzpVZ4RpYvjr6Gr9ROPnWHCBEUJA2r5zPYx7EiGCMVPLnyhktPbSwG3p7goMvQbW5bFKX67mc4Yg78uIHoKsKe5aticTi+MNv6DQhuySRL36HErCW8xKvZtlAb8jM3g9W+GgLBC2qXEC5IRn0fEF43PsQ5TwrqCkuqTG7aR+sRel1gmJGr7mGydZLITVPb2bPia2bJ1loXGBD9iELwr4cv7vTu+2tpdhffzkFL4mPb4yy8wuHC2zYazc3r1QyXaL3K1+FfeRdN6bJXMUdjQ3e1i9r5fOmir6+hv5scpcXwZJmsQ0kyGWtJ54ovMiaCKETQXqlwZAA5i41frXc2AbDe3QmR3XG88zr6U3aIf32XZNOffctWqS7SmDQ+EiXK/dl/ZQoj5nLbAgpsnC+jPIBGNvB3ObndW9R4akUwa0v0qxdlqUMpNIY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
